server:
  port: 8088

spring:
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgresql
    password: password
    url: jdbc:postgresql://localhost:5432/abb